More robust handling of grace notes and beams
rettinghaus/MEILER pull request #18
Opened 2017-01-30 01:24 UTC by th-we

More test cases and code fixing them.

2017-02-13 10:45 UTC, rettinghaus requested changes
revert `setArticulation`

2017-02-13 10:45 UTC, rettinghaus commented on mei2ly.xsl
> +  <xsl:template name="setArticulation" mode="setArticulation" match="mei:artic|*[@artic]">
Did this got in by mistake? Seems to come from another branch.

2017-03-11 11:11 UTC, rettinghaus commented
Will you work on this? Or sould I close the PR?

2017-03-11 14:55 UTC, th-we commented
Good that you remind me. I believe I'll be forced to come back to this issue for processing our material. Other things are priority right now, though.

2019-08-02 10:53 UTC, rettinghaus commented
Due to code conflicts I'm closing this for now.

2019-08-02 10:53 UTC, closed without merging